[package]
name = "benchmark"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "benchmark"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = { version = "0.9.0", features = ["logger"] }

[dev-dependencies]
marine-rs-sdk-test = "0.10.0"
